/*-------------------------------------------------------------------------*
 |                                                                         
 |            STATA SUPPLEMENTAL SYNTAX FILE FOR ICPSR 31161
 |        LAW ENFORCEMENT MANAGEMENT AND ADMINISTRATIVE STATISTICS
 |        (LEMAS): 2007 SAMPLE SURVEY OF LAW ENFORCEMENT AGENCIES
 |
 |
 | This Stata missing value recode program is provided for optional use with
 | the Stata system version of this data file as distributed by ICPSR.
 | The program replaces user-defined numeric missing values (e.g., -9)
 | with generic system missing "."  Note that Stata allows you to specify
 | up to 27 unique missing value codes.  Only variables with user-defined
 | missing values are included in this program.
 |
 | To apply the missing value recodes, users need to first open the
 | Stata data file on their system, apply the missing value recodes if
 | desired, then save a new copy of the data file with the missing values
 | applied.  Users are strongly advised to use a different filename when
 | saving the new file.
 |
 *------------------------------------------------------------------------*/

replace SWNAUTHEMP = . if (SWNAUTHEMP == 888888 | SWNAUTHEMP == 999999)
replace SWNFTEMP = . if (SWNFTEMP == 888888 | SWNFTEMP == 999999 | SWNFTEMP == 777777)
replace SWNPTEMP = . if (SWNPTEMP == 888888 | SWNPTEMP == 999999 | SWNPTEMP == 777777)
replace CIVFTEMP = . if (CIVFTEMP == 888888 | CIVFTEMP == 999999 | CIVFTEMP == 777777)
replace CIVPTEMP = . if (CIVPTEMP == 888888 | CIVPTEMP == 999999 | CIVPTEMP == 777777)
replace TOTFTEMP = . if (TOTFTEMP == 888888 | TOTFTEMP == 999999 | TOTFTEMP == 777777)
replace TOTPTEMP = . if (TOTPTEMP == 888888 | TOTPTEMP == 999999 | TOTPTEMP == 777777)
replace FTRESERVESWN = . if (FTRESERVESWN == 999999)
replace PTRESERVESWN = . if (PTRESERVESWN == 999999)
replace FTRESERVECIV = . if (FTRESERVECIV == 999999)
replace PTRESERVECIV = . if (PTRESERVECIV == 999999)
replace FTGANGOFF = . if (FTGANGOFF == 999999)
replace PTGANGOFF = . if (PTGANGOFF == 999999)
replace FTDRUGOFF = . if (FTDRUGOFF == 999999)
replace PTDRUGOFF = . if (PTDRUGOFF == 999999)
replace FTTERROFF = . if (FTTERROFF == 999999)
replace PTERROFF = . if (PTERROFF == 999999)
replace FTHUMTRFOFF = . if (FTHUMTRFOFF == 999999)
replace PTHUMTRFOFF = . if (PTHUMTRFOFF == 999999)
replace NUMRESPOFF = . if (NUMRESPOFF == 88888 | NUMRESPOFF == 99999 | NUMRESPOFF == 77777)
replace NUMCPO = . if (NUMCPO == 99999)
replace NUMSRO = . if (NUMSRO == 88888 | NUMSRO == 99999 | NUMSRO == 77777)
replace NUMPATR = . if (NUMPATR == 99999)
replace NUMINVST = . if (NUMINVST == 99999)
replace NUMJAIL = . if (NUMJAIL == 99999)
replace NUMCRTSEC = . if (NUMCRTSEC == 99999)
replace NUMPROCSERV = . if (NUMPROCSERV == 99999)
replace OPBUDGET = . if (OPBUDGET == 99999999)
replace OPBUDGEST = . if (OPBUDGEST == 8)
replace DRUGFORF = . if (DRUGFORF == 99999999)
replace GAMBFORF = . if (GAMBFORF == 9999999)
replace OTHRFORF = . if (OTHRFORF == 99999999)
replace EDREQEXM = . if (EDREQEXM == 8)
replace BACKGRND = . if (BACKGRND == 9)
replace CREDHIS = . if (CREDHIS == 9)
replace CRIMHIS = . if (CRIMHIS == 9)
replace DRIVHIS = . if (DRIVHIS == 9)
replace INTERVW = . if (INTERVW == 9)
replace PERSTEST = . if (PERSTEST == 9)
replace POLYEXAM = . if (POLYEXAM == 9)
replace PSYCHEVAL = . if (PSYCHEVAL == 9)
replace VOICESTRESS = . if (VOICESTRESS == 9)
replace WRITAPTEST = . if (WRITAPTEST == 9)
replace ANPROBSOLV = . if (ANPROBSOLV == 9)
replace CULTDIV = . if (CULTDIV == 9)
replace CONFMGT = . if (CONFMGT == 9)
replace SECLANG = . if (SECLANG == 9)
replace VOLHIS = . if (VOLHIS == 7 | VOLHIS == 9)
replace DRUGTEST = . if (DRUGTEST == 9)
replace MEDEXAM = . if (MEDEXAM == 9)
replace PHYSTEST = . if (PHYSTEST == 9)
replace TOTACAD = . if (TOTACAD == 9999)
replace TOTFIELD = . if (TOTFIELD == 9999)
replace TOTINSRV = . if (TOTINSRV == 999)
replace WHITE = . if (WHITE == 88888)
replace BLACK = . if (BLACK == 88888)
replace HISPANIC = . if (HISPANIC == 88888)
replace ASIAN = . if (ASIAN == 88888)
replace NATHAW = . if (NATHAW == 88888)
replace AMERIND = . if (AMERIND == 88888)
replace MULTRACE = . if (MULTRACE == 88888)
replace UNKRACE = . if (UNKRACE == 88888)
replace MALE = . if (MALE == 88888 | MALE == 99999)
replace FEMALE = . if (FEMALE == 88888 | FEMALE == 99999)
replace TOTGENDER = . if (TOTGENDER == 88888 | TOTGENDER == 99999)
replace SWNBILING = . if (SWNBILING == 88888 | SWNBILING == 99999)
replace CIVBILING = . if (CIVBILING == 88888 | CIVBILING == 99999)
replace SWNINTERP = . if (SWNINTERP == 9)
replace CIVINTERP = . if (CIVINTERP == 9)
replace VOLINTERP = . if (VOLINTERP == 9)
replace CONINTERP = . if (CONINTERP == 9)
replace OTHINTERP = . if (OTHINTERP == 9)
replace EDUCPAY = . if (EDUCPAY == 9)
replace HAZARDPAY = . if (HAZARDPAY == 9)
replace MERITPAY = . if (MERITPAY == 9)
replace SHIFTPAY = . if (SHIFTPAY == 9)
replace SKILLPAY = . if (SKILLPAY == 9)
replace LANGPAY = . if (LANGPAY == 9)
replace TUITIONPAY = . if (TUITIONPAY == 9)
replace MILPAY = . if (MILPAY == 9)
replace COLLBARG = . if (COLLBARG == 9)
replace RESPAY = . if (RESPAY == 9)
replace CHIEFMIN = . if (CHIEFMIN == 999999)
replace CHIEFMAX = . if (CHIEFMAX == 999999)
replace SGTMIN = . if (SGTMIN == 999999)
replace SGTMAX = . if (SGTMAX == 999999)
replace ENTRYMIN = . if (ENTRYMIN == 999999)
replace ENTRYMAX = . if (ENTRYMAX == 999999)
replace NUMWIRE = . if (NUMWIRE == 8 | NUMWIRE == 9)
replace EXACTLOC = . if (EXACTLOC == 8 | EXACTLOC == 9)
replace GENLOC = . if (GENLOC == 8 | GENLOC == 9)
replace CARPAT = . if (CARPAT == 9)
replace MOTOPAT = . if (MOTOPAT == 9)
replace FOOTPAT = . if (FOOTPAT == 9)
replace AIRPAT = . if (AIRPAT == 9)
replace BOATPAT = . if (BOATPAT == 9)
replace HORSEPAT = . if (HORSEPAT == 9)
replace BIKEPAT = . if (BIKEPAT == 9)
replace SEGPAT = . if (SEGPAT == 9)
replace OTHERPAT = . if (OTHERPAT == 9)
replace CPTRNNEW = . if (CPTRNNEW == 9 | CPTRNNEW == 8)
replace CPTRNINSERV = . if (CPTRNINSERV == 7 | CPTRNINSERV == 9)
replace CPMISSION = . if (CPMISSION == 9)
replace CPSARA = . if (CPSARA == 9)
replace CPSARANUM = . if (CPSARANUM == 8888 | CPSARANUM == 9999)
replace CPACADEMY = . if (CPACADEMY == 9)
replace CPPLAN = . if (CPPLAN == 9)
replace CPGEO = . if (CPGEO == 9)
replace CPGEONUM = . if (CPGEONUM == 8888 | CPGEONUM == 9999)
replace CPPROBSOLV = . if (CPPROBSOLV == 9)
replace CPTECHUP = . if (CPTECHUP == 9)
replace CPPARTNER = . if (CPPARTNER == 9)
replace CPSURVEY = . if (CPSURVEY == 9)
replace CPUNIT = . if (CPUNIT == 9)
replace CPNONE = . if (CPNONE == 9)
replace ADVGRP = . if (ADVGRP == 9)
replace BUSGRP = . if (BUSGRP == 9)
replace FAITHORG = . if (FAITHORG == 9)
replace LOCGOVT = . if (LOCGOVT == 9)
replace OTHLOCLEA = . if (OTHLOCLEA == 9)
replace NEIGHASC = . if (NEIGHASC == 9)
replace SENIORGRP = . if (SENIORGRP == 9)
replace SCHOOLGRP = . if (SCHOOLGRP == 9)
replace YOUTHSERV = . if (YOUTHSERV == 9)
replace EMAILMRKT = . if (EMAILMRKT == 9)
replace WEBFEEDBACK = . if (WEBFEEDBACK == 9)
replace WEBMAPS = . if (WEBMAPS == 9)
replace WEBSTATS = . if (WEBSTATS == 9)
replace LISTSERV = . if (LISTSERV == 9)
replace REV911NOT = . if (REV911NOT == 9)
replace MASSNOTNUM = . if (MASSNOTNUM == 9)
replace NONEM311 = . if (NONEM311 == 9)
replace EREPORTING = . if (EREPORTING == 9)
replace ECRIMEREP = . if (ECRIMEREP == 9)
replace OTHRCP = . if (OTHRCP == 9)
replace TERRPLAN = . if (TERRPLAN == 9)
replace INTEROP = . if (INTEROP == 9)
replace TERRPREPDIV = . if (TERRPREPDIV == 9)
replace TERRPREPFEAR = . if (TERRPREPFEAR == 9)
replace TERPREPINFO = . if (TERPREPINFO == 9)
replace TERRPREPMEET = . if (TERRPREPMEET == 9)
replace TERRPREPINCR = . if (TERRPREPINCR == 9)
replace TERRPREPEXER = . if (TERRPREPEXER == 9)
replace OTHTERRPREP = . if (OTHTERRPREP == 7 | OTHTERRPREP == 9)
replace SWNINTEL = . if (SWNINTEL == 999 | SWNINTEL == 888)
replace CIVINTEL = . if (CIVINTEL == 999 | CIVINTEL == 888)
replace SEMIPRIM = . if (SEMIPRIM == 7 | SEMIPRIM == 8 | SEMIPRIM == 9)
replace SEMIBACK = . if (SEMIBACK == 7 | SEMIBACK == 8 | SEMIBACK == 9)
replace PRIM10MM = . if (PRIM10MM == 9)
replace BACK10MM = . if (BACK10MM == 9)
replace PRIM9MM = . if (PRIM9MM == 9)
replace BACK9MM = . if (BACK9MM == 9)
replace PRIM45 = . if (PRIM45 == 9)
replace BACK45 = . if (BACK45 == 9)
replace PRIM40 = . if (PRIM40 == 9)
replace BACK40 = . if (BACK40 == 9)
replace PRIM357 = . if (PRIM357 == 9)
replace BACK357 = . if (BACK357 == 9)
replace PRIM380 = . if (PRIM380 == 9)
replace BACK380 = . if (BACK380 == 9)
replace PRIMOTHCAL = . if (PRIMOTHCAL == 9)
replace BACKOTHCAL = . if (BACKOTHCAL == 9)
replace PRIMANYSEMI = . if (PRIMANYSEMI == 9)
replace BACKANYSEMI = . if (BACKANYSEMI == 9)
replace REVOPRIM = . if (REVOPRIM == 7 | REVOPRIM == 9)
replace REVOBACK = . if (REVOBACK == 7 | REVOBACK == 9)
replace NOBACKUP = . if (NOBACKUP == 9)
replace ASSLTWEAP = . if (ASSLTWEAP == 9)
replace SHOTGUN = . if (SHOTGUN == 9)
replace CARBINE = . if (CARBINE == 9)
replace RIFLE = . if (RIFLE == 9)
replace OTHSECWP = . if (OTHSECWP == 9)
replace NOSECGUN = . if (NOSECGUN == 9)
replace NUMDOGS = . if (NUMDOGS == 999)
replace NUMHORSES = . if (NUMHORSES == 999)
replace TRADBATON = . if (TRADBATON == 9)
replace PR24BATON = . if (PR24BATON == 9)
replace COLLBATON = . if (COLLBATON == 9)
replace SOFTPROJ = . if (SOFTPROJ == 9)
replace BLACKJACK = . if (BLACKJACK == 9)
replace RUBBULLET = . if (RUBBULLET == 9)
replace OTHIMP = . if (OTHIMP == 9)
replace OCPEPPER = . if (OCPEPPER == 9)
replace OTHCHEM = . if (OTHCHEM == 9)
replace CED = . if (CED == 9)
replace NECKHOLD = . if (NECKHOLD == 9)
replace OTHNONLETH = . if (OTHNONLETH == 9)
replace DIGPRINTS = . if (DIGPRINTS == 9)
replace DIGFACEREG = . if (DIGFACEREG == 9)
replace DIGMUGSHOT = . if (DIGMUGSHOT == 9)
replace DIGPHOTO = . if (DIGPHOTO == 9)
replace DIGCOMP = . if (DIGCOMP == 9)
replace DIGNONE = . if (DIGNONE == 9)
replace INFRARED = . if (INFRARED == 9)
replace GOGGLES = . if (GOGGLES == 9)
replace IMAGEINT = . if (IMAGEINT == 9)
replace LPREADER = . if (LPREADER == 9)
replace LASERRANGE = . if (LASERRANGE == 9)
replace OPTICNONE = . if (OPTICNONE == 9)
replace ENGDISRUPT = . if (ENGDISRUPT == 9)
replace TIREDEFLATE = . if (TIREDEFLATE == 9)
replace VEHTRACK = . if (VEHTRACK == 9)
replace NOVEHSTOP = . if (NOVEHSTOP == 9)
replace NUMMRKCARS = . if (NUMMRKCARS == 99999)
replace NUMOTHMRK = . if (NUMOTHMRK == 99999)
replace NUMUMKCARS = . if (NUMUMKCARS == 99999)
replace NUMOTHUNM = . if (NUMOTHUNM == 99999)
replace NUMPLANES = . if (NUMPLANES == 99999)
replace NUMCOPTERS = . if (NUMCOPTERS == 99999)
replace NUMBOATS = . if (NUMBOATS == 99999)
replace NUMMOTOR = . if (NUMMOTOR == 99999)
replace TAKEHOME = . if (TAKEHOME == 8 | TAKEHOME == 9)
replace PERSUSE = . if (PERSUSE == 8 | PERSUSE == 9)
replace OUTSIDEJUR = . if (OUTSIDEJUR == 8 | OUTSIDEJUR == 9)
replace VIDCAM = . if (VIDCAM == 9)
replace NUMCARCAM = . if (NUMCARCAM == 9999)
replace NUMFIXCAM = . if (NUMFIXCAM == 9999)
replace NUMMOBCAM = . if (NUMMOBCAM == 9999)
replace SHOTSENSOR = . if (SHOTSENSOR == 9)
replace NUMSENSOR = . if (NUMSENSOR == 8888 | NUMSENSOR == 9999)
replace COMCOMMPROB = . if (COMCOMMPROB == 9)
replace COMBOOKING = . if (COMBOOKING == 9)
replace COMCRIMANL = . if (COMCRIMANL == 9)
replace COMCRIMEMAP = . if (COMCRIMEMAP == 9)
replace COMINVEST = . if (COMINVEST == 9)
replace COMCAD = . if (COMCAD == 9)
replace COMFLEET = . if (COMFLEET == 9)
replace COMHOTSPOT = . if (COMHOTSPOT == 9)
replace COMINFCOMM = . if (COMINFCOMM == 9)
replace COMINFWRIT = . if (COMINFWRIT == 9)
replace COMINTEL = . if (COMINTEL == 9)
replace COMINFOSHAR = . if (COMINFOSHAR == 9)
replace COMINTERNET = . if (COMINTERNET == 9)
replace COMPERSREC = . if (COMPERSREC == 9)
replace COMRECMAN = . if (COMRECMAN == 9)
replace COMRESALLO = . if (COMRESALLO == 9)
replace COMNONE = . if (COMNONE == 9)
replace ALARMFILES = . if (ALARMFILES == 9)
replace ARRESTFILES = . if (ARRESTFILES == 9)
replace BIOMETFILES = . if (BIOMETFILES == 9)
replace CFSFILES = . if (CFSFILES == 9)
replace CMPLNTFILES = . if (CMPLNTFILES == 9)
replace PRINTFILES = . if (PRINTFILES == 9)
replace INCREPFILES = . if (INCREPFILES == 9)
replace GUNFILES = . if (GUNFILES == 9)
replace INTELFILES = . if (INTELFILES == 9)
replace PROPFILES = . if (PROPFILES == 9)
replace SUMMFILES = . if (SUMMFILES == 9)
replace TRAFCITFILES = . if (TRAFCITFILES == 9)
replace TRAFSTOPFILES = . if (TRAFSTOPFILES == 9)
replace USEFORCEFILES = . if (USEFORCEFILES == 9)
replace WARRANTFILES = . if (WARRANTFILES == 9)
replace GANGFILES = . if (GANGFILES == 9)
replace PAWNFILES = . if (PAWNFILES == 9)
replace PROTORDFILES = . if (PROTORDFILES == 9)
replace NONEFILES = . if (NONEFILES == 9)
replace USEINFCOM = . if (USEINFCOM == 9)
replace NUMPERM = . if (NUMPERM == 88888 | NUMPERM == 99999)
replace NUMDOCK = . if (NUMDOCK == 88888 | NUMDOCK == 99999)
replace NUMPORT = . if (NUMPORT == 88888 | NUMPORT == 99999)
replace MVRECACC = . if (MVRECACC == 9)
replace DRIVRECACC = . if (DRIVRECACC == 9)
replace CRIMRECACC = . if (CRIMRECACC == 9)
replace WARRRANTACC = . if (WARRRANTACC == 9)
replace PROTORDACC = . if (PROTORDACC == 9)
replace INFOSHARACC = . if (INFOSHARACC == 9)
replace ADDRINFOACC = . if (ADDRINFOACC == 9)
replace WEBACC = . if (WEBACC == 9)
replace GISMAPACC = . if (GISMAPACC == 9)
replace OTHERACC = . if (OTHERACC == 9)
replace TRANSMIT = . if (TRANSMIT >= 7 & TRANSMIT <= 9)
replace AFISOWNER = . if (AFISOWNER == 9)
replace AFISTERM = . if (AFISTERM == 9)
replace AFISOTHER = . if (AFISOTHER == 9)
replace AFISNONE = . if (AFISNONE == 9)
replace EARLYWARN = . if (EARLYWARN == 9)
replace DEADFORCPLCY = . if (DEADFORCPLCY == 9)
replace LESSTHANPLCY = . if (LESSTHANPLCY == 9)
replace CODECONDPLCY = . if (CODECONDPLCY == 9)
replace OFFDEMPLPLCY = . if (OFFDEMPLPLCY == 9)
replace MAXHOURSPLCY = . if (MAXHOURSPLCY == 9)
replace OFFDCONDPLCY = . if (OFFDCONDPLCY == 9)
replace MEDIAPLCY = . if (MEDIAPLCY == 9)
replace EAPPLCY = . if (EAPPLCY == 9)
replace MENTILLPLCY = . if (MENTILLPLCY == 9)
replace HOMELESSPLCY = . if (HOMELESSPLCY == 9)
replace DOMDISPPLCY = . if (DOMDISPPLCY == 9)
replace JUVENILEPLCY = . if (JUVENILEPLCY == 9)
replace LIMITENGPLCY = . if (LIMITENGPLCY == 9)
replace INCUSDTHPLCY = . if (INCUSDTHPLCY == 9)
replace RACIALPRPLCY = . if (RACIALPRPLCY == 9)
replace CITCOMPPLCY = . if (CITCOMPPLCY == 9)
replace IMMSTATPLCY = . if (IMMSTATPLCY == 9)
replace NUMUOFSUST = . if (NUMUOFSUST == 77777 | NUMUOFSUST == 99999)
replace NUMUOFOTH = . if (NUMUOFOTH == 77777 | NUMUOFOTH == 99999)
replace NUMUOFPEND = . if (NUMUOFPEND == 77777 | NUMUOFPEND == 99999)
replace NUMUOFTOT = . if (NUMUOFTOT == 77777 | NUMUOFTOT == 99999)
replace CCRB = . if (CCRB == 9)
replace CCRBPOWERS = . if (CCRBPOWERS == 9)
replace OUTSIDEINV = . if (OUTSIDEINV == 9)


