/*-------------------------------------------------------------------------*
 |                                                                         
 |            STATA SUPPLEMENTAL SYNTAX FILE FOR ICPSR 36164
 |        LAW ENFORCEMENT MANAGEMENT AND ADMINISTRATIVE STATISTICS
 |                             (LEMAS), 2013
 |
 |
 | This Stata missing value recode program is provided for optional use with
 | the Stata system version of this data file as distributed by ICPSR.
 | The program replaces user-defined numeric missing values (e.g., -9)
 | with generic system missing "."  Note that Stata allows you to specify
 | up to 27 unique missing value codes.  Only variables with user-defined
 | missing values are included in this program.
 |
 | To apply the missing value recodes, users need to first open the
 | Stata data file on their system, apply the missing value recodes if
 | desired, then save a new copy of the data file with the missing values
 | applied.  Users are strongly advised to use a different filename when
 | saving the new file.
 |
 *------------------------------------------------------------------------*/

replace ORI7 = "" if (ORI7 == "-1")
replace FTSWORN = . if (FTSWORN == -9)
replace FTCIV = . if (FTCIV == -9)
replace PTSWORN = . if (PTSWORN == -9)
replace PTCIV = . if (PTCIV == -9)
replace PERS_PDSW_MFT = . if (PERS_PDSW_MFT == -9)
replace PERS_PDSW_MPT = . if (PERS_PDSW_MPT == -9)
replace PERS_PDSW_FFT = . if (PERS_PDSW_FFT == -9)
replace PERS_PDSW_FPT = . if (PERS_PDSW_FPT == -9)
replace PERS_FTS_WHT = . if (PERS_FTS_WHT == -9)
replace PERS_FTS_BLK = . if (PERS_FTS_BLK == -9)
replace PERS_FTS_HSP = . if (PERS_FTS_HSP == -9)
replace PERS_FTS_IND = . if (PERS_FTS_IND == -9)
replace PERS_FTS_ASN = . if (PERS_FTS_ASN == -9)
replace PERS_FTS_HAW = . if (PERS_FTS_HAW == -9)
replace PERS_FTS_TWO = . if (PERS_FTS_TWO == -9)
replace PERS_FTS_UNK = . if (PERS_FTS_UNK == -9)
replace PERS_FTS_RACETOT = . if (PERS_FTS_RACETOT == -9.00)
replace PERS_RESP_PATRL = . if (PERS_RESP_PATRL == -9)
replace PERS_RESP_INVST = . if (PERS_RESP_INVST == -9)
replace PERS_RESP_JAIL = . if (PERS_RESP_JAIL == -9 | PERS_RESP_JAIL == -8)
replace PERS_RESP_CRT = . if (PERS_RESP_CRT == -9)
replace PERS_RESP_OTHR = . if (PERS_RESP_OTHR == -9 | PERS_RESP_OTHR == -8)
replace PERS_SUP_CHF_M = . if (PERS_SUP_CHF_M == -9)
replace PERS_SUP_CHF_F = . if (PERS_SUP_CHF_F == -9)
replace PERS_SUP_INTM_M = . if (PERS_SUP_INTM_M == -9 | PERS_SUP_INTM_M == -8)
replace PERS_SUP_INTM_F = . if (PERS_SUP_INTM_F == -9 | PERS_SUP_INTM_F == -8)
replace PERS_SUP_SGT_M = . if (PERS_SUP_SGT_M == -9 | PERS_SUP_SGT_M == -8)
replace PERS_SUP_SGT_F = . if (PERS_SUP_SGT_F == -9 | PERS_SUP_SGT_F == -8)
replace PERS_SSW_FT = . if (PERS_SSW_FT == -9)
replace PERS_SSW_PT = . if (PERS_SSW_PT == -9)
replace PERS_UPSW = . if (PERS_UPSW == -9)
replace PERS_DUT_NONE = . if (PERS_DUT_NONE == -9)
replace PERS_DUT_ADMN = . if (PERS_DUT_ADMN == -8 | PERS_DUT_ADMN == -9)
replace PERS_DUT_CLN = . if (PERS_DUT_CLN == -8 | PERS_DUT_CLN == -9)
replace PERS_DUT_LGL = . if (PERS_DUT_LGL == -8 | PERS_DUT_LGL == -9)
replace PERS_DUT_ACCT = . if (PERS_DUT_ACCT == -8 | PERS_DUT_ACCT == -9)
replace PERS_DUT_FSCI = . if (PERS_DUT_FSCI == -8 | PERS_DUT_FSCI == -9)
replace PERS_DUT_RSRCH = . if (PERS_DUT_RSRCH == -8 | PERS_DUT_RSRCH == -9)
replace PERS_DUT_HR = . if (PERS_DUT_HR == -8 | PERS_DUT_HR == -9)
replace PERS_DUT_IT = . if (PERS_DUT_IT == -8 | PERS_DUT_IT == -9)
replace PERS_DUT_VM = . if (PERS_DUT_VM == -8 | PERS_DUT_VM == -9)
replace PERS_DUT_CD = . if (PERS_DUT_CD == -8 | PERS_DUT_CD == -9)
replace PERS_DUT_CRT = . if (PERS_DUT_CRT == -8 | PERS_DUT_CRT == -9)
replace PERS_DUT_JAIL = . if (PERS_DUT_JAIL == -8 | PERS_DUT_JAIL == -9)
replace PERS_DUT_OTHR = . if (PERS_DUT_OTHR == -8 | PERS_DUT_OTHR == -9)
replace PERS_DUT_SPEC = "" if (PERS_DUT_SPEC == "-9")
replace PAY_SAL_EXC_MIN = . if (PAY_SAL_EXC_MIN == -9 | PAY_SAL_EXC_MIN == -8)
replace PAY_SAL_EXC_MAX = . if (PAY_SAL_EXC_MAX == -9 | PAY_SAL_EXC_MAX == -8)
replace PAY_SAL_SGT_MIN = . if (PAY_SAL_SGT_MIN == -9 | PAY_SAL_SGT_MIN == -8)
replace PAY_SAL_SGT_MAX = . if (PAY_SAL_SGT_MAX == -9 | PAY_SAL_SGT_MAX == -8)
replace PAY_SAL_OFCR_MIN = . if (PAY_SAL_OFCR_MIN == -9 | PAY_SAL_OFCR_MIN == -8)
replace PAY_SAL_OFCR_MAX = . if (PAY_SAL_OFCR_MAX == -9 | PAY_SAL_OFCR_MAX == -8)
replace PAY_INCT_EDU = . if (PAY_INCT_EDU == -9)
replace PAY_INCT_VOC = . if (PAY_INCT_VOC == -9)
replace PAY_INCT_LANG = . if (PAY_INCT_LANG == -9)
replace PAY_INCT_SPCL = . if (PAY_INCT_SPCL == -9)
replace PAY_INCT_HZRD = . if (PAY_INCT_HZRD == -9)
replace PAY_INCT_SD = . if (PAY_INCT_SD == -9)
replace PAY_INCT_RINC = . if (PAY_INCT_RINC == -9)
replace PAY_INCT_MRT = . if (PAY_INCT_MRT == -9)
replace PAY_INCT_OTHR = . if (PAY_INCT_OTHR == -9)
replace PAY_INCT_SPEC = "" if (PAY_INCT_SPEC == "-9")
replace PAY_OUT = . if (PAY_OUT == -9)
replace PAY_RST_NO = . if (PAY_RST_NO == -9 | PAY_RST_NO == -8)
replace PAY_RST_HRS = . if (PAY_RST_HRS == -9 | PAY_RST_HRS == -8)
replace PAY_RST_TYPE = . if (PAY_RST_TYPE == -9 | PAY_RST_TYPE == -8)
replace PAY_RST_OTHR = . if (PAY_RST_OTHR == -9 | PAY_RST_OTHR == -8)
replace PAY_RST_SPEC = "" if (PAY_RST_SPEC == "-9")
replace PAY_BARG = . if (PAY_BARG == -9)
replace PAY_SBARG = . if (PAY_SBARG == -9 | PAY_SBARG == -8)
replace PAY_RMB_TUIT = . if (PAY_RMB_TUIT == -9)
replace PAY_RMB_UNF = . if (PAY_RMB_UNF == -9)
replace PAY_RMB_ARMR = . if (PAY_RMB_ARMR == -9)
replace PAY_RMB_SFTY = . if (PAY_RMB_SFTY == -9)
replace PAY_RMB_FIRE = . if (PAY_RMB_FIRE == -9)
replace PAY_OVER_SW = . if (PAY_OVER_SW == -9)
replace PAY_OVER_NSW = . if (PAY_OVER_NSW == -9)
replace PAY_FUNC_CRT = . if (PAY_FUNC_CRT == -9 | PAY_FUNC_CRT == -8)
replace PAY_FUNC_SHFT = . if (PAY_FUNC_SHFT == -9 | PAY_FUNC_SHFT == -8)
replace PAY_FUNC_PTRL = . if (PAY_FUNC_PTRL == -9 | PAY_FUNC_PTRL == -8)
replace PAY_FUNC_INVS = . if (PAY_FUNC_INVS == -9 | PAY_FUNC_INVS == -8)
replace PAY_FUNC_ADMN = . if (PAY_FUNC_ADMN == -9 | PAY_FUNC_ADMN == -8)
replace PAY_FUNC_EMRG = . if (PAY_FUNC_EMRG == -9 | PAY_FUNC_EMRG == -8)
replace PAY_FUNC_EVNT = . if (PAY_FUNC_EVNT == -9 | PAY_FUNC_EVNT == -8)
replace PAY_FUNC_OTHR = . if (PAY_FUNC_OTHR == -9 | PAY_FUNC_OTHR == -8)
replace PAY_FUNC_SPEC = "" if (PAY_FUNC_SPEC == "-9")
replace PAY_LMT = . if (PAY_LMT == -9)
replace PAY_VEH_MRK = . if (PAY_VEH_MRK == -9)
replace PAY_VEH_UMRK = . if (PAY_VEH_UMRK == -9)
replace HIR_FRZ = . if (HIR_FRZ == -9)
replace HIR_MTH_SW10 = . if (HIR_MTH_SW10 == -9 | HIR_MTH_SW10 == -8)
replace HIR_MTH_SW11 = . if (HIR_MTH_SW11 == -9 | HIR_MTH_SW11 == -8)
replace HIR_MTH_SW12 = . if (HIR_MTH_SW12 == -9 | HIR_MTH_SW12 == -8)
replace HIR_MTH_NSW10 = . if (HIR_MTH_NSW10 == -9.00 | HIR_MTH_NSW10 == -8.00)
replace HIR_MTH_NSW11 = . if (HIR_MTH_NSW11 == -9.0 | HIR_MTH_NSW11 == -8.0)
replace HIR_MTH_NSW12 = . if (HIR_MTH_NSW12 == -9.0 | HIR_MTH_NSW12 == -8.0)
replace HIR_NBR = . if (HIR_NBR == -9)
replace HIR_NBR_DRCT_FT = . if (HIR_NBR_DRCT_FT == -9 | HIR_NBR_DRCT_FT == -8)
replace HIR_NBR_DRCT_PT = . if (HIR_NBR_DRCT_PT == -9 | HIR_NBR_DRCT_PT == -8)
replace HIR_NBR_PRE_FT = . if (HIR_NBR_PRE_FT == -9 | HIR_NBR_PRE_FT == -8)
replace HIR_NBR_PRE_PT = . if (HIR_NBR_PRE_PT == -9 | HIR_NBR_PRE_PT == -8)
replace HIR_NBR_LAT_FT = . if (HIR_NBR_LAT_FT == -9 | HIR_NBR_LAT_FT == -8)
replace HIR_NBR_LAT_PT = . if (HIR_NBR_LAT_PT == -9 | HIR_NBR_LAT_PT == -8)
replace HIR_NBR_TFT = . if (HIR_NBR_TFT == -9 | HIR_NBR_TFT == -8)
replace HIR_NBR_TPT = . if (HIR_NBR_TPT == -9 | HIR_NBR_TPT == -8)
replace HIR_TRN_NO_L = . if (HIR_TRN_NO_L == -9)
replace HIR_TRN_NO_P = . if (HIR_TRN_NO_P == -9)
replace HIR_TRN_CRS_L = . if (HIR_TRN_CRS_L == -9)
replace HIR_TRN_CRS_P = . if (HIR_TRN_CRS_P == -9)
replace HIR_TRN_FLD_L = . if (HIR_TRN_FLD_L == -9)
replace HIR_TRN_FLD_P = . if (HIR_TRN_FLD_P == -9)
replace HIR_TRN_DIR_L = . if (HIR_TRN_DIR_L == -9)
replace HIR_TRN_DIR_P = . if (HIR_TRN_DIR_P == -9)
replace HIR_TRN_OLATS = "" if (HIR_TRN_OLATS == "-9")
replace HIR_TRN_OPRES = "" if (HIR_TRN_OPRES == "-9")
replace HIR_NSWT_NO = . if (HIR_NSWT_NO == -9)
replace HIR_NSWT_VAR_FT = . if (HIR_NSWT_VAR_FT == -9 | HIR_NSWT_VAR_FT == -8)
replace HIR_NSWT_VAR_PT = . if (HIR_NSWT_VAR_PT == -9.0 | HIR_NSWT_VAR_PT == -8.0)
replace HIR_EDU_NO = . if (HIR_EDU_NO == -9)
replace HIR_EDU_HS = . if (HIR_EDU_HS == -9)
replace HIR_EDU_SCOL = . if (HIR_EDU_SCOL == -9)
replace HIR_EDU_AD = . if (HIR_EDU_AD == -9)
replace HIR_EDU_BD = . if (HIR_EDU_BD == -9)
replace HIR_EDU_OTHR = . if (HIR_EDU_OTHR == -9)
replace HIR_EDU_SPEC = "" if (HIR_EDU_SPEC == "-9")
replace HIR_MIL = . if (HIR_MIL == -9 | HIR_MIL == -8)
replace HIR_BD_VAR = . if (HIR_BD_VAR == -9 | HIR_BD_VAR == -8)
replace HIR_RTR_DB = . if (HIR_RTR_DB == -9)
replace HIR_RTR_DC = . if (HIR_RTR_DC == -9)
replace HIR_RTR_SS = . if (HIR_RTR_SS == -9)
replace HIR_RTR_OTHR = . if (HIR_RTR_OTHR == -9)
replace HIR_RTR_SPEC = "" if (HIR_RTR_SPEC == "-9")
replace HIR_SEP_NMED = . if (HIR_SEP_NMED == -9)
replace HIR_SEP_MED = . if (HIR_SEP_MED == -9)
replace HIR_SEP_VOL = . if (HIR_SEP_VOL == -9)
replace HIR_SEP_LAYOFF = . if (HIR_SEP_LAYOFF == -9)
replace HIR_SEP_DIS = . if (HIR_SEP_DIS == -9)
replace HIR_SEP_OTHR = . if (HIR_SEP_OTHR == -9)
replace HIR_SEP_TTL = . if (HIR_SEP_TTL == -9)
replace HIR_SEPNS_LAYOFF = . if (HIR_SEPNS_LAYOFF == -9)
replace HIR_SEPNS_OTHR = . if (HIR_SEPNS_OTHR == -9)
replace HIR_SEPNS_TTL = . if (HIR_SEPNS_TTL == -9)
replace BDGT_MNTH = . if (BDGT_MNTH == -9)
replace BDGT_TTL = . if (BDGT_TTL == -9)
replace BDGT_SRC_MNC = . if (BDGT_SRC_MNC == -9)
replace BDGT_SRC_CNTY = . if (BDGT_SRC_CNTY == -9)
replace BDGT_SRC_STATE = . if (BDGT_SRC_STATE == -9)
replace BDGT_SRC_FED = . if (BDGT_SRC_FED == -9)
replace BDGT_SRC_CONT = . if (BDGT_SRC_CONT == -9)
replace BDGT_SRC_ASST = . if (BDGT_SRC_ASST == -9)
replace BDGT_SRC_FEE = . if (BDGT_SRC_FEE == -9)
replace BDGT_SRC_OTHR = . if (BDGT_SRC_OTHR == -9)
replace BDGT_SRC_SPEC = "" if (BDGT_SRC_SPEC == "-9")
replace BDGT_RED = . if (BDGT_RED == -9)
replace BDGT_PCT_SW = . if (BDGT_PCT_SW == -9.00 | BDGT_PCT_SW == -8.00)
replace BDGT_PCT_NSW = . if (BDGT_PCT_NSW == -9.00 | BDGT_PCT_NSW == -8.00)
replace BDGT_FUR = . if (BDGT_FUR == -9)
replace BDGT_FUR2_SW10 = . if (BDGT_FUR2_SW10 == -9 | BDGT_FUR2_SW10 == -8)
replace BDGT_FUR2_SW11 = . if (BDGT_FUR2_SW11 == -9 | BDGT_FUR2_SW11 == -8)
replace BDGT_FUR2_SW12 = . if (BDGT_FUR2_SW12 == -9 | BDGT_FUR2_SW12 == -8)
replace BDGT_FUR2_NSW10 = . if (BDGT_FUR2_NSW10 == -9 | BDGT_FUR2_NSW10 == -8)
replace BDGT_FUR2_NSW11 = . if (BDGT_FUR2_NSW11 == -9 | BDGT_FUR2_NSW11 == -8)
replace BDGT_FUR2_NSW12 = . if (BDGT_FUR2_NSW12 == -9 | BDGT_FUR2_NSW12 == -8)
replace COM_MIS = . if (COM_MIS == -9)
replace COM_TRN_REC = . if (COM_TRN_REC == -8 | COM_TRN_REC == -9)
replace COM_TRN_INSRV = . if (COM_TRN_INSRV == -8 | COM_TRN_INSRV == -9)
replace COM_SARA = . if (COM_SARA == -9 | COM_SARA == -8)
replace COM_NSARA = . if (COM_NSARA == -9 | COM_NSARA == -8)
replace COM_COL = . if (COM_COL == -9)
replace COM_PTNR = . if (COM_PTNR == -9)
replace COM_BT = . if (COM_BT == -9)
replace COM_NBT = . if (COM_NBT == -9 | COM_NBT == -8)
replace COM_SURV = . if (COM_SURV == -9)
replace TECH_TYP_GUN = . if (TECH_TYP_GUN == -9)
replace TECH_TYP_LIC = . if (TECH_TYP_LIC == -9)
replace TECH_TYP_SMRT = . if (TECH_TYP_SMRT == -9)
replace TECH_TYP_VPUB = . if (TECH_TYP_VPUB == -9)
replace TECH_TYP_VVEH = . if (TECH_TYP_VVEH == -9)
replace TECH_TYP_VPAT = . if (TECH_TYP_VPAT == -9)
replace TECH_TYP_VWPN = . if (TECH_TYP_VWPN == -9)
replace TECH_TYP_VOTHR = . if (TECH_TYP_VOTHR == -9)
replace TECH_EAC_MREC = . if (TECH_EAC_MREC == -9)
replace TECH_EAC_DREC = . if (TECH_EAC_DREC == -9)
replace TECH_EAC_CRIM = . if (TECH_EAC_CRIM == -9)
replace TECH_EAC_WARR = . if (TECH_EAC_WARR == -9)
replace TECH_EAC_PROT = . if (TECH_EAC_PROT == -9)
replace TECH_EAC_ADRS = . if (TECH_EAC_ADRS == -9)
replace TECH_CIR = . if (TECH_CIR == -9)
replace TECH_CIR_SPEC = "" if (TECH_CIR_SPEC == "-9")
replace TECH_CRS = . if (TECH_CRS == -9)
replace TECH_CREC_INC = . if (TECH_CREC_INC == -9 | TECH_CREC_INC == -8)
replace TECH_CREC_SUM = . if (TECH_CREC_SUM == -9 | TECH_CREC_SUM == -8)
replace TECH_CREC_NAR = . if (TECH_CREC_NAR == -9 | TECH_CREC_NAR == -8)
replace TECH_CREC_OTHR = . if (TECH_CREC_OTHR == -9 | TECH_CREC_OTHR == -8)
replace TECH_CREC_SPEC = "" if (TECH_CREC_SPEC == "-9")
replace TECH_REC_NAR = . if (TECH_REC_NAR == -9 | TECH_REC_NAR == -8)
replace TECH_REC_CODE = . if (TECH_REC_CODE == -9 | TECH_REC_CODE == -8)
replace TECH_REC_STAT = . if (TECH_REC_STAT == -9 | TECH_REC_STAT == -8)
replace TECH_REC_VIC = . if (TECH_REC_VIC == -9 | TECH_REC_VIC == -8)
replace TECH_REC_SUS = . if (TECH_REC_SUS == -9 | TECH_REC_SUS == -8)
replace TECH_REC_LOC = . if (TECH_REC_LOC == -9 | TECH_REC_LOC == -8)
replace TECH_REC_GEO = . if (TECH_REC_GEO == -9 | TECH_REC_GEO == -8)
replace TECH_REC_DATE = . if (TECH_REC_DATE == -9 | TECH_REC_DATE == -8)
replace TECH_WHO_NO = . if (TECH_WHO_NO == -9)
replace TECH_WHO_STAFF = . if (TECH_WHO_STAFF == -9 | TECH_WHO_STAFF == -8)
replace TECH_WHO_EXTR = . if (TECH_WHO_EXTR == -9 | TECH_WHO_EXTR == -8)
replace TECH_MANY_FTS = . if (TECH_MANY_FTS == -9 | TECH_MANY_FTS == -8)
replace TECH_MANY_PTS = . if (TECH_MANY_PTS == -9 | TECH_MANY_PTS == -8)
replace TECH_MANY_FTNS = . if (TECH_MANY_FTNS == -9 | TECH_MANY_FTNS == -8)
replace TECH_MANY_PTNS = . if (TECH_MANY_PTNS == -9 | TECH_MANY_PTNS == -8)
replace TECH_OUT_LAW = . if (TECH_OUT_LAW == -9 | TECH_OUT_LAW == -8)
replace TECH_OUT_GOV = . if (TECH_OUT_GOV == -9 | TECH_OUT_GOV == -8)
replace TECH_OUT_UNIV = . if (TECH_OUT_UNIV == -9 | TECH_OUT_UNIV == -8)
replace TECH_OUT_VEND = . if (TECH_OUT_VEND == -9 | TECH_OUT_VEND == -8)
replace TECH_OUT_OTHR = . if (TECH_OUT_OTHR == -9 | TECH_OUT_OTHR == -8)
replace TECH_OUT_OTHR_SPEC = "" if (TECH_OUT_OTHR_SPEC == "-9")
replace TECH_WEB_NONE = . if (TECH_WEB_NONE == -9 | TECH_WEB_NONE == -8)
replace TECH_WEB_JUR = . if (TECH_WEB_JUR == -9 | TECH_WEB_JUR == -8)
replace TECH_WEB_BEAT = . if (TECH_WEB_BEAT == -9 | TECH_WEB_BEAT == -8)
replace TECH_WEB_MAP = . if (TECH_WEB_MAP == -9 | TECH_WEB_MAP == -8)
replace TECH_WEB_OFFND = . if (TECH_WEB_OFFND == -9 | TECH_WEB_OFFND == -8)
replace TECH_WEB_OTHR = . if (TECH_WEB_OTHR == -9 | TECH_WEB_OTHR == -8)
replace TECH_WEB_SPEC = "" if (TECH_WEB_SPEC == "-9")
replace TECH_PUBL_REP = . if (TECH_PUBL_REP == -9 | TECH_PUBL_REP == -8)
replace TECH_PUBL_ASK = . if (TECH_PUBL_ASK == -9 | TECH_PUBL_ASK == -8)
replace TECH_PUBL_FILE = . if (TECH_PUBL_FILE == -9 | TECH_PUBL_FILE == -8)
replace TECH_PUBL_OTHR = . if (TECH_PUBL_OTHR == -9 | TECH_PUBL_OTHR == -8)
replace TECH_PUBL_SPEC = "" if (TECH_PUBL_SPEC == "-9")
replace TECH_REPT = . if (TECH_REPT == -9)
replace TECH_RECV = . if (TECH_RECV == -9)
replace TECH_MEDIA_TW = . if (TECH_MEDIA_TW == -9)
replace TECH_MEDIA_FB = . if (TECH_MEDIA_FB == -9)
replace TECH_MEDIA_BLOG = . if (TECH_MEDIA_BLOG == -9)
replace TECH_MEDIA_YTBE = . if (TECH_MEDIA_YTBE == -9)
replace TECH_MEDIA_MASS = . if (TECH_MEDIA_MASS == -9)
replace TECH_MEDIA_OTHR = . if (TECH_MEDIA_OTHR == -9)
replace TECH_MEDIA_SPEC = "" if (TECH_MEDIA_SPEC == "-9")
replace VEH_OPRT_MK = . if (VEH_OPRT_MK == -9)
replace VEH_OPRT_UNMK = . if (VEH_OPRT_UNMK == -9)
replace VEH_TYP_MTR = . if (VEH_TYP_MTR == -9)
replace VEH_TYP_ATV = . if (VEH_TYP_ATV == -9)
replace VEH_TYP_AIR = . if (VEH_TYP_AIR == -9)
replace VEH_TYP_HCOP = . if (VEH_TYP_HCOP == -9)
replace VEH_TYP_BOAT = . if (VEH_TYP_BOAT == -9)
replace VEH_TYP_DRONE = . if (VEH_TYP_DRONE == -9)
replace VEH_TYP_OTHR = . if (VEH_TYP_OTHR == -9)
replace VEH_TYP_SPEC = "" if (VEH_TYP_SPEC == "-9")
replace VEH_WPUR = . if (VEH_WPUR == -9)
replace VEH_WPUR_SPEC = "" if (VEH_WPUR_SPEC == "-9")
replace VEH_DOC = . if (VEH_DOC == -9)
replace VEH_DOC_SPEC = "" if (VEH_DOC_SPEC == "-9")
replace VEH_NPUR = . if (VEH_NPUR == -9)
replace VEH_REST_ALN = . if (VEH_REST_ALN == -8)
replace VEH_REST_VISL = . if (VEH_REST_VISL == -8)
replace VEH_REST_SEPR = . if (VEH_REST_SEPR == -8)
replace VEH_REST_RADIO = . if (VEH_REST_RADIO == -8)
replace VEH_REST_ARM = . if (VEH_REST_ARM == -8)
replace VEH_REST_OTHR = . if (VEH_REST_OTHR == -8)
replace VEH_REST_SPEC = "" if (VEH_REST_SPEC == "-9")
replace VEH_CNTN = . if (VEH_CNTN == -8)
replace SAFE_AUTH_HGN = . if (SAFE_AUTH_HGN == -9)
replace SAFE_AUTH_RFL = . if (SAFE_AUTH_RFL == -9)
replace SAFE_AUTH_SGN = . if (SAFE_AUTH_SGN == -9)
replace SAFE_AUTH_BTN = . if (SAFE_AUTH_BTN == -9)
replace SAFE_AUTH_IMP = . if (SAFE_AUTH_IMP == -9)
replace SAFE_AUTH_SOFT = . if (SAFE_AUTH_SOFT == -9)
replace SAFE_AUTH_SPRAY = . if (SAFE_AUTH_SPRAY == -9)
replace SAFE_AUTH_CHEM = . if (SAFE_AUTH_CHEM == -9)
replace SAFE_AUTH_TASR = . if (SAFE_AUTH_TASR == -9)
replace SAFE_AUTH_NECK = . if (SAFE_AUTH_NECK == -9)
replace SAFE_AUTH_TKDWN = . if (SAFE_AUTH_TKDWN == -9)
replace SAFE_AUTH_OHAND = . if (SAFE_AUTH_OHAND == -9)
replace SAFE_AUTH_CHAND = . if (SAFE_AUTH_CHAND == -9)
replace SAFE_AUTH_LEG = . if (SAFE_AUTH_LEG == -9)
replace SAFE_DOC_DISF = . if (SAFE_DOC_DISF == -8)
replace SAFE_DOC_DCHF = . if (SAFE_DOC_DCHF == -8)
replace SAFE_DOC_BAT = . if (SAFE_DOC_BAT == -8)
replace SAFE_DOC_IMP = . if (SAFE_DOC_IMP == -8)
replace SAFE_DOC_SOFT = . if (SAFE_DOC_SOFT == -8)
replace SAFE_DOC_SPRAY = . if (SAFE_DOC_SPRAY == -8)
replace SAFE_DOC_CHEM = . if (SAFE_DOC_CHEM == -8)
replace SAFE_DOC_DIST = . if (SAFE_DOC_DIST == -8)
replace SAFE_DOC_DCHT = . if (SAFE_DOC_DCHT == -8)
replace SAFE_DOC_NECK = . if (SAFE_DOC_NECK == -8)
replace SAFE_DOC_TKDWN = . if (SAFE_DOC_TKDWN == -8)
replace SAFE_DOC_OHAND = . if (SAFE_DOC_OHAND == -8)
replace SAFE_DOC_CHAND = . if (SAFE_DOC_CHAND == -8)
replace SAFE_DOC_LEG = . if (SAFE_DOC_LEG == -8)
replace SAFE_FINC = . if (SAFE_FINC == -9)
replace SAFE_FINC_SPEC = "" if (SAFE_FINC_SPEC == "-9")
replace SAFE_FRC_INC = . if (SAFE_FRC_INC == -8)
replace SAFE_FRC_OFFC = . if (SAFE_FRC_OFFC == -8)
replace SAFE_FRC_OTHR = . if (SAFE_FRC_OTHR == -8)
replace SAFE_FRC_SPEC = "" if (SAFE_FRC_SPEC == "-9")
replace SAFE_FTTL = . if (SAFE_FTTL == -9 | SAFE_FTTL == -8 | SAFE_FTTL == -3)
replace SAFE_SEPR = . if (SAFE_SEPR == -9 | SAFE_SEPR == -8 | SAFE_SEPR == -3)
replace SAFE_ARMR_OTHRS = . if (SAFE_ARMR_OTHRS == -9)
replace SAFE_RQUR_ACC = . if (SAFE_RQUR_ACC == -8)
replace SAFE_RQUR_RSK = . if (SAFE_RQUR_RSK == -8)
replace SAFE_RQUR_ALL = . if (SAFE_RQUR_ALL == -8)
replace SAFE_RQUR_CSTM = . if (SAFE_RQUR_CSTM == -8)
replace SAFE_RQUR_TRN = . if (SAFE_RQUR_TRN == -8)
replace SAFE_RQUR_COMP = . if (SAFE_RQUR_COMP == -8)
replace SAFE_RQUR_BLST = . if (SAFE_RQUR_BLST == -8)
replace SAFE_PAY_DPT = . if (SAFE_PAY_DPT == -8)
replace SAFE_PAY_IND = . if (SAFE_PAY_IND == -8)
replace SAFE_PAY_GRNT = . if (SAFE_PAY_GRNT == -8)
replace SAFE_PAY_OTHR = . if (SAFE_PAY_OTHR == -8)
replace SAFE_PAY_SPEC = "" if (SAFE_PAY_SPEC == "-9")
replace ISSU_ADDR_BIAS = . if (ISSU_ADDR_BIAS == -9)
replace ISSU_ADDR_BOMB = . if (ISSU_ADDR_BOMB == -9)
replace ISSU_ADDR_ABSE = . if (ISSU_ADDR_ABSE == -9)
replace ISSU_ADDR_CYBR = . if (ISSU_ADDR_CYBR == -9)
replace ISSU_ADDR_DPV = . if (ISSU_ADDR_DPV == -9)
replace ISSU_ADDR_TERR = . if (ISSU_ADDR_TERR == -9)
replace ISSU_ADDR_TRAF = . if (ISSU_ADDR_TRAF == -9)
replace ISSU_ADDR_DUI = . if (ISSU_ADDR_DUI == -9)
replace ISSU_ADDR_JUV = . if (ISSU_ADDR_JUV == -9)
replace ISSU_ADDR_GANG = . if (ISSU_ADDR_GANG == -9)
replace ISSU_ADDR_REEN = . if (ISSU_ADDR_REEN == -9)
replace ISSU_ADDR_FUG = . if (ISSU_ADDR_FUG == -9)
replace ISSU_ADDR_VIC = . if (ISSU_ADDR_VIC == -9)
replace ISSU_ADDR_SWAT = . if (ISSU_ADDR_SWAT == -9)
replace ISSU_SPEC = . if (ISSU_SPEC == -9)
replace ISSU_MULTI = . if (ISSU_MULTI == -9)
replace ISSU_TASK_SWAT = . if (ISSU_TASK_SWAT == -8)
replace ISSU_TASK_DRUG = . if (ISSU_TASK_DRUG == -8)
replace ISSU_TASK_GANG = . if (ISSU_TASK_GANG == -8)
replace ISSU_TASK_TRAF = . if (ISSU_TASK_TRAF == -8)
replace ISSU_TASK_OTHR = . if (ISSU_TASK_OTHR == -8)
replace ISSU_TASK_SPEC = "" if (ISSU_TASK_SPEC == "-9")


